version: '3'
services:
  loki:
    image: grafana/loki:2.5.0
    container_name: loki
    volumes:
      - ./loki/data:/loki
      - ./loki/config.yaml:/etc/loki/local-config.yaml
  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    container_name: grafana
  vector:
    image: timberio/vector:0.X-alpine
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml
    container_name: vector
    depends_on:
      - loki
  traffic_scraper:
    image: vi0oss/websocat:0.10.0
    container_name: traffic_scraper
    command: -v --autoreconnect-delay-millis 15000 autoreconnect:ws://$CLASH_HOST/traffic?token=$CLASH_TOKEN autoreconnect:tcp:vector:9000
    depends_on:
      - vector
  tracing_scraper:
    image: vi0oss/websocat:0.10.0
    container_name: tracing_scraper
    command: -v --autoreconnect-delay-millis 15000 autoreconnect:ws://$CLASH_HOST/profile/tracing?token=$CLASH_TOKEN autoreconnect:tcp:vector:9000
    depends_on:
      - vector
